# 系统配置
system:
  # Fast api是否开启调试模式
  DEBUG: true
  LOG_LEVEL: "DEBUG"


FASTAPI_CONFIG:
  TITLE: "RankPilot编排系统"
  DESCRIPTION: "这是一个前后端分离的编排系统"
  HOST: "0.0.0.0"
  PORT: 9100
  VERSION: "1.0.0"

db:
  REDIS_DB:
    REDIS_USERNAME: ""
    REDIS_PASSWORD: ""
    REDIS_HOST: "localhost"
    REDIS_PORT: 6379
    REDIS_DB: 1
    REDIS_DB_ENABLE: true

  ORM_DB:
    DB_ECHO: False
    DB_HOST: "192.168.110.40"
    DB_PORT: 5432
    DB_USERNAME: "postgres"
    DB_PASSWORD: "123456"
    DB_SCHEMA: "postgresql+asyncpg"
    DB_NAME: "pgtest"

    POOL_SIZE: 10

MINIO_CONFIG:
  HOST: "oss.ethersky.cn"
  ACCESS_KEY: "bq2UMqo6viqJOTEeM4OH"
  SECRET_KEY: "RkhTZOk5eWNJO7NGesYQ3WL2az4Ft3NfJxv7JwKG"

RABBITMQ_CONFIG:
  RABBITMQ_URL: "amqp://guest:guest@localhost:5672/"




